# Generated by Django 2.1.1 on 2019-10-14 08:58

import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clasificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetos', models.CharField(choices=[('Coche', 'Coche'), ('Semáforo', 'Semáforo'), ('Señal', 'Señal'), ('Otros', 'Otros')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('coordinatex', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('coordinatey', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('coordinatez', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('path', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True, verbose_name=django.contrib.auth.models.User)),
                ('Nombre', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to='documents/')),
                ('numb', models.IntegerField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gps_northing', models.IntegerField(blank=True, null=True)),
                ('gps_easting', models.IntegerField(blank=True, null=True)),
                ('layers', models.IntegerField(default=32)),
                ('gps_lat', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=10), blank=True, null=True, size=3)),
                ('gps_long', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=10), blank=True, null=True, size=3)),
            ],
        ),
    ]
