# Generated by Django 2.1.1 on 2019-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_auto_20191015_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificador',
            name='coordinatex',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clasificador',
            name='coordinatey',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clasificador',
            name='coordinatez',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
