# Generated by Django 2.1.1 on 2019-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_auto_20191028_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificador',
            name='coordinatex',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clasificador',
            name='coordinatey',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clasificador',
            name='coordinatez',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
